
version: 2

sources:
  - name: raw

    tables:
      - name: :product
        description: ürün bilgileri tablosu

        columns:
          - name: products_id
            tests:
              - not_null
              - unique
          - name: purchase_price
      - name: sales
        description: satış bilgileri tablosu
        columns:
          - name: date_date
            tests:
              - not_null
          - name: orders_is
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: revenue
          - name: qty
      - name: ship
        description: kargo bilgileri tablosu

        columns:
          - name: orders_id
            tests:
              - not_null
          - name: shipping_fee
          - name: shipping_fee1
          - name: log_cost
          - name: ship_cost
          